version: '3.0'
services:
  webapp:
    container_name: webapp
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    links:
      - "redis:redis.webapp.com"
    ports:
      - "8080:8080"
  redis:
   container_name: some-redis
   image: redis